name = "afp-site"
compatibility_date = "2024-01-01"

# Cloudflare Pages configuration
pages_build_output_dir = "dist"

# SPA fallback configuration
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
